### ISSUE TITLE
version 0.5 don't show any command in vscode

### ISSUE THREAD

**Issue by xjy198903** [microhobby/linuxkerneldev#30]
version 0.5 don't show any command in vscode

**Comment by flavioamieiro** [comment]
I have the same issue. I'm running vs code version 1.74.3 and the extension in version 0.5.0:

![2023-01-25-144658_1814x803_scrot](https://user-images.githubusercontent.com/60641/214580276-05f85b6b-f321-4d0a-a1d4-6d55c7d76a9f.png)

The `runtime status` tab in the extensions menu says `_callBackShow is not a function`: 


![2023-01-25-144915_1933x644_scrot](https://user-images.githubusercontent.com/60641/214580474-fafd7eb5-3f67-4dcd-bb4e-ef81872ad37d.png)

**Comment by microhobby** [comment]
Hi @flavioamieiro and @xjy198903, I was able to reproduce here, working in a fix. Thanks for the report.

**Comment by microhobby** [comment]
The `v0.5.1` version with the fix are already published in VS Marketplace. Thanks!

**Comment by flavioamieiro** [comment]
@microhobby I can confirm v0.5.1 as installed from the VS Marketplace works perfectly on vscode version 1.75.0

Thank you very much for the fix!
